### ISSUE TITLE
Refactoring request: %w(a b c) --> ["a", "b", "c"]

### ISSUE THREAD

**Issue by ryanseys** [JavierGelatti/RubyRefactorings#1]
First of all, love the plugin! Here's an idea for a refactoring idea:

`%w(a b c)` --> `["a", "b", "c"]`

Let me know what you think!

**Comment by JavierGelatti** [comment]
@ryanseys thanks a lot for the suggestion! :raised_hands:

There are many refactorings that are only implemented one-way by RubyMine, like this one (RubyMine only implements `["a", "b", "c"]` -> `%w[a b c]`), but it's always nice to have the inverse available too!

**Comment by JavierGelatti** [comment]
@ryanseys I implemented the refactoring you suggested (for both `%w` and `%i` literals) in [the last release](https://github.com/JavierGelatti/RubyRefactorings/releases/tag/v0.1.9)!

![Convert %w and %i literals to square bracket array](https://plugins.jetbrains.com/files/15312/screenshot_0ef20c09-71cf-4740-8f56-c8b19cff2e1e)

The update should be available in JetBrain's marketplace in ~1 day

Enjoy! :sparkles:

**Comment by ryanseys** [comment]
Thank you!! :)
